### ISSUE TITLE
Using dp-transformers models for inference

### ISSUE THREAD

**Issue by zredlined** [microsoft/dp-transformers#25]
I am trying to load a fine-tuned model from dp-transformers for inference but am receiving the error below, which appears to be due to overloading the default Trainer model with the GradSampleModule from Opacus, which is not backwards compatible with the HF model's generate functions. Can you share any feedback or examples about how to prompt the DP models for text generation? 

Thanks in advance.

Example code:
```
# Save the model to the disk
trainer.save_model(output_dir=train_args.output_dir)

# Generation
prompt_text = "The answer to the great question of Life, the Universe and Everything is"
encoded_prompt = tokenizer.encode(prompt_text, add_special_tokens=False, return_tensors="pt")
generated_sequences = trainer.model.generate(encoded_prompt, max_length=100, temperature=1.0)

# Decode it
generated_sequences = generated_sequences[0].tolist()
text = tokenizer.decode(generated_sequences, clean_up_tokenization_spaces=True)
print(text)
```

Error:
```
[INFO|trainer.py:1786] 2023-06-26 17:13:28,916 >> ***** Running training *****
[INFO|trainer.py:1787] 2023-06-26 17:13:28,916 >>   Num examples = 980
[INFO|trainer.py:1788] 2023-06-26 17:13:28,916 >>   Num Epochs = 3
[INFO|trainer.py:1789] 2023-06-26 17:13:28,916 >>   Instantaneous batch size per device = 64
[INFO|trainer.py:1790] 2023-06-26 17:13:28,916 >>   Total train batch size (w. parallel, distributed & accumulation) = 64
[INFO|trainer.py:1791] 2023-06-26 17:13:28,916 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1792] 2023-06-26 17:13:28,916 >>   Total optimization steps = 45
[INFO|trainer.py:1793] 2023-06-26 17:13:28,917 >>   Number of trainable parameters = 147,456

...

{'loss': 3.9738, 'learning_rate': 0.0003, 'epoch': 3.0}
[INFO|trainer.py:3200] 2023-06-26 17:14:16,735 >> ***** Running Evaluation *****
[INFO|trainer.py:3202] 2023-06-26 17:14:16,735 >>   Num examples = 20
[INFO|trainer.py:3205] 2023-06-26 17:14:16,735 >>   Batch size = 64
[WARNING|logging.py:280] 2023-06-26 17:14:16,789 >> You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
{'eval_runtime': 0.1748, 'eval_samples_per_second': 114.414, 'eval_steps_per_second': 5.721, 'epoch': 3.0}
[INFO|trainer.py:2053] 2023-06-26 17:14:17,119 >> 

Training completed. Do not forget to share your model on huggingface.co/models =)

{'train_runtime': 48.203, 'train_samples_per_second': 60.992, 'train_steps_per_second': 0.934, 'train_loss': 4.016973029242622, 'epoch': 3.0}
{'final_epsilon_prv': 7.815436928174181, 'final_epsilon_rdp': 9.690711958418493, 'epoch': 3.0}
[INFO|trainer.py:2926] 2023-06-26 17:14:17,324 >> Saving model checkpoint to scratch
[INFO|trainer.py:2940] 2023-06-26 17:14:17,326 >> Trainer.model is not a `PreTrainedModel`, only saving its state dict.
Traceback (most recent call last):
  File "/home/redlined/dp-transformers/fine-tune-dp.py", line 192, in <module>
    main(Arguments(train=train_args, privacy=privacy_args, model=model_args, dataset=dataset_args))
  File "/home/redlined/dp-transformers/fine-tune-dp.py", line 183, in main
    generated_sequences = trainer.model.generate(encoded_prompt, max_length=100, temperature=1.0)
  File "/opt/conda/envs/dp/lib/python3.10/site-packages/opacus/grad_sample/gsm_base.py", line 77, in __getattr__
    raise e
  File "/opt/conda/envs/dp/lib/python3.10/site-packages/opacus/grad_sample/gsm_base.py", line 72, in __getattr__
    return super().__getattr__(item)
  File "/opt/conda/envs/dp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GradSampleModule' object has no attribute 'generate'
```

**Comment by huseyinatahaninan** [comment]
Hello @zredlined, could you please let me know the version of HF and Opacus you have and whether the training was distributed or single GPU?

**Comment by huseyinatahaninan** [comment]
You may just need to do `trainer.model._module.generate` as `GradSampleModule` holds the model under `._module`

**Comment by zredlined** [comment]
Thanks, your suggestion worked. I hadn't realized the model was being held under `model._module`. 

To answer the first question about HF and opacus libs, I'm running:
```
opacus==1.2.0
transformers==4.30.2
```

**Comment by huseyinatahaninan** [comment]
Glad that it helps. On a separate note, I had not tested recent versions of transformers for a while and now noticing that our repo works until the version 4.28.1 (we just updated setup.py). Beyond this version `accelerator` comes into play and leads to errors with our integration (especially in the gradient accumulation case). I am not sure how much effort it'd take to make changes that would work with `accelerator` so just wanted to give heads up about this.
