### ISSUE TITLE
Integrating opacus with huggingface

### ISSUE THREAD

**Issue by SoumiDas** [microsoft/dp-transformers#45]
Hello,

I was trying to see if the Opacus library can be used with the Trainer module of huggingface. I see a code snippet in the readme that says to do the callback ```dp_transformers.PrivacyEngineCallback``` in the Trainer module. However, it leads to an error that says the callback does not exist. I was unable to figure it out in the source code either. 

It would be really helpful if I could be pointed to the part of the source code that has this callback or maybe guide me with any solution for the error.

Thanks!

**Comment by huseyinatahaninan** [comment]
Hi @SoumiDas, indeed this repo is all about integrating Opacus library with the Trainer module of HF. Have you seen these examples by any chance? https://github.com/microsoft/dp-transformers/tree/main/research/fine_tune_llm_w_qlora -- here we provide examples of DP training with the Trainer module of HF (https://github.com/microsoft/dp-transformers/blob/main/research/fine_tune_llm_w_qlora/fine-tune-dp.py). Let us know please if you have further questions.

You can see here https://github.com/microsoft/dp-transformers/blob/main/src/dp_transformers/dp_utils.py where we create OpacusDPTrainer from the HF Trainer and where the DPCallback is added.

**Comment by dooohow** [comment]
Hi @huseyinatahaninan, wonderful work. But could you tell me about the compatible version of Opacus? The API of PrivacyEngine in Opacus seems have changed in the latest version of Opacus. I found some problem using it. Is dp-transformers still compatible with it?
Thanks!

**Comment by huseyinatahaninan** [comment]
I think it should work with 1.4.1 but I have not used a version beyond that so I am not sure if it's compatible with 1.5 or not.

**Comment by dooohow** [comment]
Actually I am running **analysing_pii_leakage**, which is a repository using your **dp_transformers** in dp training of gpt2. But I failed to run their example. 
There is a `TypeError: OpacusDPTrainer.training_step() takes 3 positional arguments but 4 were given`

![Image](https://github.com/user-attachments/assets/80b1a384-cb23-4b23-bae3-434c719c99be)

I can't get responses from them, so I wondering if you can offer some help or suggestions? Thanks a lot.
> I think it should work with 1.4.1 but I have not used a version beyond that so I am not sure if it's compatible with 1.5 or not.

**Comment by dooohow** [comment]
> I think it should work with 1.4.1 but I have not used a version beyond that so I am not sure if it's compatible with 1.5 or not.

I downgraded the version of tranformers to 4.43.0 instead of 4.47.0. The previous problem disappeared, and a new error appeared. `RuntimeError: You are trying to call the hook of a dead Module!`
```
Traceback (most recent call last):
  File "/home/duhao/analysing_pii_leakage/examples/fine_tune.py", line 81, in <module>
    fine_tune(*parse_args())
  File "/home/duhao/analysing_pii_leakage/examples/fine_tune.py", line 73, in fine_tune
    lm.fine_tune(train_dataset, eval_dataset, train_args, privacy_args)
  File "/home/duhao/analysing_pii_leakage/src/pii_leakage/models/language_model.py", line 298, in fine_tune
    return self._fine_tune_dp(train_dataset, eval_dataset, train_args, privacy_args)
  File "/home/duhao/analysing_pii_leakage/src/pii_leakage/models/language_model.py", line 278, in _fine_tune_dp
    trainer.train()
  File "/home/duhao/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/home/duhao/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/duhao/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/dp_transformers/dp_utils.py", line 264, in training_step
    loss.backward()
  File "/home/duhao/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/duhao/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/duhao/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/torch/nn/modules/module.py", line 61, in __call__
    raise RuntimeError("You are trying to call the hook of a dead Module!")
RuntimeError: You are trying to call the hook of a dead Module!
```

**Comment by papaya0481** [comment]
The recent version of `transformers` (i.e. `>=4.46.0`) has implemented `training_step` through 
```
def training_step(
        self, model: nn.Module, inputs: Dict[str, Union[torch.Tensor, Any]], num_items_in_batch=None
    ) -> torch.Tensor:
```
which take 4 positional arguments (including `self`). However, the `training_step` in `dp_transformers.dp_utils.OpacusDPTrainer` implemented as 
```
def training_step(self, model: nn.Module, inputs: Dict[str, Union[torch.Tensor, Any]]) -> torch.Tensor:
```
which takes only 3 positional arguments. Hence it raises error.

Is there any way to solve it without downgrading transformers version?

Hopefully it can be fixed soon.
