### ISSUE TITLE
example author-level-dp error

### ISSUE THREAD

**Issue by edifice1989** [microsoft/dp-transformers#51]
Here is my command:

running on a single local GPU

python fine-tune-dp.py \
--output_dir scratch \
--model_name gpt2 \
--sequence_len 128 \
--per_device_train_batch_size 64 \
--gradient_accumulation_steps 1 \
--evaluation_strategy steps \
--eval_steps 45 \
--log_level info \
--per_device_eval_batch_size 64 \
--eval_accumulation_steps 1 \
--seed 42 \
--target_epsilon 8 \
--per_sample_max_grad_norm 1.0 \
--prediction_loss_only \
--weight_decay 0.01 \
--remove_unused_columns False \
--num_train_epochs 3 \
--logging_steps 5 \
--lora_dim 4 \
--lora_alpha 32 \
--lora_dropout 0.0 \
--max_grad_norm 0 \
--lr_scheduler_type constant \
--learning_rate 3e-4 \
--disable_tqdm True \
--dataloader_num_workers 2 \
--label_names labels \
--enable_lora

Traceback (most recent call last):
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dp-transformers_github/examples/nlg-reddit/author-level-dp/fine-tune-dp.py", line 160, in <module>
    main(Arguments(train=train_args, privacy=privacy_args, model=model_args, lora=lora_args))
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dp-transformers_github/examples/nlg-reddit/author-level-dp/fine-tune-dp.py", line 148, in main
    trainer.train()
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/transformers/trainer.py", line 2052, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/transformers/trainer.py", line 2467, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/transformers/trainer.py", line 2918, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/transformers/trainer.py", line 3008, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/transformers/trainer.py", line 3623, in save_model
    self._save(output_dir)
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/transformers/trainer.py", line 3721, in _save
    safetensors.torch.save_file(
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/safetensors/torch.py", line 286, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
                   ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Ming/Desktop/DP/code/dp_transformer/dptransformer/lib/python3.11/site-packages/safetensors/torch.py", line 488, in _flatten
    raise RuntimeError(
RuntimeError:
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'_module.base_model.model.lm_head.weight', '_module.base_model.model.transformer.wte.weight'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors

**Comment by huseyinatahaninan** [comment]
Hmmm this does not seem to be related to DP. Just did a quick online search and maybe you can give it a try this: https://github.com/hiyouga/LLaMA-Factory/issues/3400

--save_safetensors False

**Comment by edifice1989** [comment]
thanks, it works: )

**Comment by edifice1989** [comment]
thanks, it works: )
